name: .NET CI Build

on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/common.yml

  deploy-nuget:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 🔫 Build All
        run: ./build.sh
