name: .NET Build and Publish

on:
  push:
    branches: ["main"] 

jobs:
  build:
    uses: ./.github/workflows/ci.yml

  deploy-nuget:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 🔫 Build Nuget
        run: echo "test"
