name: .NET Build and Publish

on:
  push:
    branches: ["main"] 

jobs:
  build:
    uses: ./.github/workflows/common.yml

  deploy-nuget:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 🔫 Build and Pack
        run: ./build.sh pack
